{"name": "TC010_Login with invalid credentials", "status": "broken", "statusDetails": {"message": "AttributeError: 'SauceDemoLoginPage' object has no attribute 'self'", "trace": "fixturefunc = <function verify_not_able_to_login at 0x000002BFB41E71A0>\nrequest = <FixtureRequest for <Function test_report_tc10[standard_user-U0g3UlNLNkZXTkZDTEREUEVDUUJPNVpDNEk=]>>\nkwargs = {}\n\n    def call_fixture_func(\n        fixturefunc: _FixtureFunc[FixtureValue], request: FixtureRequest, kwargs\n    ) -> FixtureValue:\n        if is_generator(fixturefunc):\n            fixturefunc = cast(\n                Callable[..., Generator[FixtureValue, None, None]], fixturefunc\n            )\n            generator = fixturefunc(**kwargs)\n            try:\n                fixture_result = next(generator)\n            except StopIteration:\n                raise ValueError(f\"{request.fixturename} did not yield a value\") from None\n            finalizer = functools.partial(_teardown_yield_fixture, fixturefunc, generator)\n            request.addfinalizer(finalizer)\n        else:\n            fixturefunc = cast(Callable[..., FixtureValue], fixturefunc)\n>           fixture_result = fixturefunc(**kwargs)\n\nvenv\\Lib\\site-packages\\_pytest\\fixtures.py:897: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntests\\test_cases\\test_saucedemo.py:112: in verify_not_able_to_login\n    text = sdl.get_error_msg()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <src.pom.pages.saucedemo_login_page.SauceDemoLoginPage object at 0x000002BFB3668790>\n\n    def get_error_msg(self):\n        time.sleep(3)\n        log.info(\"Get error message after login failure\")\n        with allure.step(\"Get error message after login failure\"):\n>           error_message = self.self.get_text_by_xpath(By.XPATH, errorMessage)\nE           AttributeError: 'SauceDemoLoginPage' object has no attribute 'self'\n\nsrc\\pom\\pages\\saucedemo_login_page.py:38: AttributeError"}, "description": "D:\\Project\\QE_JavaPython\\framework_python\\test_py_web\\tests\\test_cases\\..\\features\\sauce_demo.feature: TC010_Login with invalid credentials", "steps": [{"name": "Login into sauce demo using id and password", "status": "passed", "start": 1723446720075, "stop": 1723446720363}, {"name": "Click login button", "status": "passed", "start": 1723446723369, "stop": 1723446723439}, {"name": "Get error message after login failure", "status": "broken", "statusDetails": {"message": "AttributeError: 'SauceDemoLoginPage' object has no attribute 'self'\n", "trace": "  File \"D:\\Project\\QE_JavaPython\\framework_python\\test_py_web\\src\\pom\\pages\\saucedemo_login_page.py\", line 38, in get_error_msg\n    error_message = self.self.get_text_by_xpath(By.XPATH, errorMessage)\n                    ^^^^^^^^^\n"}, "start": 1723446726442, "stop": 1723446726442}], "attachments": [{"name": "log", "source": "d61d43ef-940e-44a8-9557-7ddfa56ae23a-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "3fe0093f-426d-4193-b9ef-e7102989f7d8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "_pytest_bdd_example", "value": "{'username': 'standard_user', 'pwd': 'U0g3UlNLNkZXTkZDTEREUEVDUUJPNVpDNEk='}"}], "start": 1723446710068, "stop": 1723446726442, "uuid": "16832cb4-6c03-45c5-9f4f-30ad91d8b984", "historyId": "67334d44a5552305012f5847043e852b", "testCaseId": "f376bf8030f727c3a79ad66993d326d4", "fullName": "tests.test_cases.test_saucedemo#test_report_tc10", "labels": [{"name": "feature", "value": "Validate Login Credentials"}, {"name": "severity", "value": "blocker"}, {"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "tests.test_cases"}, {"name": "suite", "value": "test_saucedemo"}, {"name": "host", "value": "TIGER04836"}, {"name": "thread", "value": "16576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cases.test_saucedemo"}]}