{"name": "TC010_Login with invalid credentials", "status": "broken", "statusDetails": {"message": "pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: When \"Login with uuid_base32hb and c2VjcmV0X3NhdWNl\". Line 5 in scenario \"TC010_Login with invalid credentials\" in the feature \"D:\\Project\\QE_JavaPython\\framework_python\\test_py_web\\tests\\features\\sauce_demo.feature\"", "trace": "E   pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: When \"Login with uuid_base32hb and c2VjcmV0X3NhdWNl\". Line 5 in scenario \"TC010_Login with invalid credentials\" in the feature \"D:\\Project\\QE_JavaPython\\framework_python\\test_py_web\\tests\\features\\sauce_demo.feature\"\nAll traceback entries are hidden. Pass `--full-trace` to see hidden and internal frames."}, "description": "D:\\Project\\QE_JavaPython\\framework_python\\test_py_web\\tests\\test_cases\\..\\features\\sauce_demo.feature: TC010_Login with invalid credentials", "attachments": [{"name": "stdout", "source": "00d45af2-793a-4c3e-b04f-06940af6feb9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "_pytest_bdd_example", "value": "{'username': 'uuid_base32hb', 'pwd': 'c2VjcmV0X3NhdWNl'}"}], "start": 1723446277410, "stop": 1723446284415, "uuid": "3756c635-c3d9-4120-996a-48ebdc10647d", "historyId": "6d1ebb14dab67d935cbe1b533f9c36cc", "testCaseId": "f376bf8030f727c3a79ad66993d326d4", "fullName": "tests.test_cases.test_saucedemo#test_report_tc10", "labels": [{"name": "severity", "value": "blocker"}, {"name": "feature", "value": "Validate Login Credentials"}, {"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "tests.test_cases"}, {"name": "suite", "value": "test_saucedemo"}, {"name": "host", "value": "TIGER04836"}, {"name": "thread", "value": "4796-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cases.test_saucedemo"}]}