{"name": "TC010_Login with invalid credentials", "status": "broken", "statusDetails": {"message": "pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"Login to dashboard for Test Case: \"tc10\"\". Line 4 in scenario \"TC010_Login with invalid credentials\" in the feature \"D:\\Project\\QE_JavaPython\\framework_python\\test_py_web\\tests\\features\\sauce_demo.feature\"", "trace": "E   pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"Login to dashboard for Test Case: \"tc10\"\". Line 4 in scenario \"TC010_Login with invalid credentials\" in the feature \"D:\\Project\\QE_JavaPython\\framework_python\\test_py_web\\tests\\features\\sauce_demo.feature\"\nAll traceback entries are hidden. Pass `--full-trace` to see hidden and internal frames."}, "description": "D:\\Project\\QE_JavaPython\\framework_python\\test_py_web\\tests\\test_cases\\..\\features\\sauce_demo.feature: TC010_Login with invalid credentials", "parameters": [{"name": "_pytest_bdd_example", "value": "{'username': 'uuid_base32hb', 'pwd': 'c2VjcmV0X3NhdWNl'}"}], "start": 1723445583245, "stop": 1723445583246, "uuid": "7b6914e9-0223-4e39-8107-35fbb4bee0d0", "historyId": "6d1ebb14dab67d935cbe1b533f9c36cc", "testCaseId": "f376bf8030f727c3a79ad66993d326d4", "fullName": "tests.test_cases.test_saucedemo#test_report_tc10", "labels": [{"name": "feature", "value": "Validate Login Credentials"}, {"name": "severity", "value": "blocker"}, {"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "tests.test_cases"}, {"name": "suite", "value": "test_saucedemo"}, {"name": "host", "value": "TIGER04836"}, {"name": "thread", "value": "25628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cases.test_saucedemo"}]}