{"name": "TC010_Login with invalid credentials", "status": "broken", "statusDetails": {"message": "pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"Login to dashboard for Test Case: \"tc10\"\". Line 4 in scenario \"TC010_Login with invalid credentials\" in the feature \"D:\\Project\\QE_JavaPython\\framework_python\\test_py_web\\tests\\features\\sauce_demo.feature\"", "trace": "E   pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"Login to dashboard for Test Case: \"tc10\"\". Line 4 in scenario \"TC010_Login with invalid credentials\" in the feature \"D:\\Project\\QE_JavaPython\\framework_python\\test_py_web\\tests\\features\\sauce_demo.feature\"\nAll traceback entries are hidden. Pass `--full-trace` to see hidden and internal frames."}, "description": "D:\\Project\\QE_JavaPython\\framework_python\\test_py_web\\tests\\test_cases\\..\\features\\sauce_demo.feature: TC010_Login with invalid credentials", "parameters": [{"name": "_pytest_bdd_example", "value": "{'username': 'standard_user', 'pwd': 'U0g3UlNLNkZXTkZDTEREUEVDUUJPNVpDNEk='}"}], "start": 1723445577402, "stop": 1723445577403, "uuid": "dfa4a916-34d2-4b68-b290-697b3c84aace", "historyId": "67334d44a5552305012f5847043e852b", "testCaseId": "f376bf8030f727c3a79ad66993d326d4", "fullName": "tests.test_cases.test_saucedemo#test_report_tc10", "labels": [{"name": "feature", "value": "Validate Login Credentials"}, {"name": "severity", "value": "blocker"}, {"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "tests.test_cases"}, {"name": "suite", "value": "test_saucedemo"}, {"name": "host", "value": "TIGER04836"}, {"name": "thread", "value": "25628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cases.test_saucedemo"}]}